//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.DriverAllocations = new HashSet<DriverAllocation>();
            this.DutySlips = new HashSet<DutySlip>();
        }
    
        public long bookingId { get; set; }
        public int branchId { get; set; }
        public string bookingType { get; set; }
        public string billAddress { get; set; }
        public string bookingNumber { get; set; }
        public System.DateTime bookingDate { get; set; }
        public string billingType { get; set; }
        public int bookingReceivedBy { get; set; }
        public Nullable<int> partyId { get; set; }
        public string bookingBy { get; set; }
        public Nullable<int> guestId { get; set; }
        public string guestMobileNo { get; set; }
        public string bookingSource { get; set; }
        public Nullable<System.DateTime> requirementStartDate { get; set; }
        public Nullable<System.DateTime> requirementEndDate { get; set; }
        public string travelId { get; set; }
        public string reportingTo { get; set; }
        public string reportingMobileNo { get; set; }
        public string reportingLocation { get; set; }
        public Nullable<System.TimeSpan> reportingTime { get; set; }
        public Nullable<int> carModelId { get; set; }
        public Nullable<int> dutyTypeId { get; set; }
        public string specialInstruction { get; set; }
        public Nullable<bool> requisition { get; set; }
        public string mobileNumber1 { get; set; }
        public string mobileNumber2 { get; set; }
        public string mobileNumber3 { get; set; }
        public bool active { get; set; }
        public int entryBy { get; set; }
        public System.DateTime entryDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<int> guestAddressId { get; set; }
        public Nullable<int> allocationId { get; set; }
    
        public virtual CarModel CarModel { get; set; }
        public virtual CompanyBranch CompanyBranch { get; set; }
        public virtual DutyType DutyType { get; set; }
        public virtual Guest Guest { get; set; }
        public virtual Party Party { get; set; }
        public virtual guestAddress guestAddress { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverAllocation> DriverAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DutySlip> DutySlips { get; set; }
    }
}
