//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.DriverAllocations = new HashSet<DriverAllocation>();
            this.DutySlips = new HashSet<DutySlip>();
        }
    
        public int CarId { get; set; }
        public Nullable<int> branchId { get; set; }
        public string carType { get; set; }
        public Nullable<int> carModelId { get; set; }
        public string fuelTypeCode { get; set; }
        public string carNumber { get; set; }
        public Nullable<int> driverId { get; set; }
        public string registrationNumber { get; set; }
        public string chasisNumber { get; set; }
        public string engineNumber { get; set; }
        public string insuranceCompany { get; set; }
        public string insurancePolicyNo { get; set; }
        public Nullable<System.DateTime> insuranceStartDate { get; set; }
        public Nullable<System.DateTime> insuranceEndDate { get; set; }
        public Nullable<System.DateTime> taxStartDate { get; set; }
        public Nullable<System.DateTime> taxEndDate { get; set; }
        public Nullable<System.DateTime> authorisationStartDate { get; set; }
        public Nullable<System.DateTime> authorisationEndDate { get; set; }
        public Nullable<System.DateTime> fitnessStartDate { get; set; }
        public Nullable<System.DateTime> fitnessEndDate { get; set; }
        public Nullable<System.DateTime> permitStartDate { get; set; }
        public Nullable<System.DateTime> permitEndDate { get; set; }
        public Nullable<System.DateTime> pucStartDate { get; set; }
        public Nullable<System.DateTime> pucEndDate { get; set; }
        public string financeBy { get; set; }
        public Nullable<int> ownerId { get; set; }
        public bool carInUse { get; set; }
        public bool carOnHold { get; set; }
        public Nullable<int> servicingSlab { get; set; }
        public Nullable<decimal> emiAmount { get; set; }
        public Nullable<System.DateTime> emiDate { get; set; }
        public bool active { get; set; }
        public int entryBy { get; set; }
        public System.DateTime entryDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    
        public virtual CarModel CarModel { get; set; }
        public virtual CompanyBranch CompanyBranch { get; set; }
        public virtual FuelType FuelType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverAllocation> DriverAllocations { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Party Party { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DutySlip> DutySlips { get; set; }
    }
}
