//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CarRentalEntities : DbContext
    {
        public CarRentalEntities()
            : base("name=CarRentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyBranch> CompanyBranches { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<PartyStatu> PartyStatus { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<CarModel> CarModels { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<FuelType> FuelTypes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Scheme> Schemes { get; set; }
        public virtual DbSet<DutyType> DutyTypes { get; set; }
        public virtual DbSet<RateCard> RateCards { get; set; }
        public virtual DbSet<ExpenseHead> ExpenseHeads { get; set; }
        public virtual DbSet<ReleasePoint> ReleasePoints { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<guestAddress> guestAddresses { get; set; }
        public virtual DbSet<DriverAllocation> DriverAllocations { get; set; }
        public virtual DbSet<DutySlip> DutySlips { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sp_Generate_BookingNo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Generate_BookingNo");
        }
    }
}
