//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DutySlipDetail
    {
        public long dutySlipDetailId { get; set; }
        public long dutySlipId { get; set; }
        public Nullable<int> schemeId { get; set; }
        public Nullable<System.TimeSpan> billOpeningTime { get; set; }
        public Nullable<System.TimeSpan> billClosingTime { get; set; }
        public Nullable<decimal> billOpeningKm { get; set; }
        public Nullable<decimal> billClosingKm { get; set; }
        public Nullable<decimal> dayAllowance { get; set; }
        public Nullable<decimal> nightAllowance { get; set; }
        public Nullable<decimal> extraKm { get; set; }
        public Nullable<decimal> extraKmAmount { get; set; }
        public Nullable<decimal> extraHour { get; set; }
        public Nullable<decimal> extraHourAmount { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
    
        public virtual DutySlip DutySlip { get; set; }
        public virtual Scheme Scheme { get; set; }
    }
}
