//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Logins = new HashSet<Login>();
            this.Bookings = new HashSet<Booking>();
            this.DriverAllocations = new HashSet<DriverAllocation>();
            this.Cars = new HashSet<Car>();
            this.DutySlips = new HashSet<DutySlip>();
        }
    
        public int employeeId { get; set; }
        public string employeeCode { get; set; }
        public int branchId { get; set; }
        public Nullable<int> designationId { get; set; }
        public string employeeName { get; set; }
        public string residentiallAddress { get; set; }
        public string nativeAddress { get; set; }
        public string mobileNumber { get; set; }
        public string residentialTelephone { get; set; }
        public System.DateTime joiningDate { get; set; }
        public Nullable<System.DateTime> leavingDate { get; set; }
        public Nullable<decimal> basicAmount { get; set; }
        public Nullable<decimal> hraAmount { get; set; }
        public Nullable<decimal> ccAmount { get; set; }
        public string bloodGroup { get; set; }
        public string licenseNumber { get; set; }
        public Nullable<decimal> otRatePerHour { get; set; }
        public Nullable<decimal> outstation150 { get; set; }
        public Nullable<decimal> outstation100 { get; set; }
        public Nullable<decimal> pfAmount { get; set; }
        public Nullable<decimal> extraDuty { get; set; }
        public string accountNumber { get; set; }
        public bool active { get; set; }
        public int entryBy { get; set; }
        public System.DateTime entryDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<decimal> sundayAmount { get; set; }
    
        public virtual CompanyBranch CompanyBranch { get; set; }
        public virtual Designation Designation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Logins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverAllocation> DriverAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car> Cars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DutySlip> DutySlips { get; set; }
    }
}
