//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guest()
        {
            this.Bookings = new HashSet<Booking>();
            this.guestAddresses = new HashSet<guestAddress>();
        }
    
        public int guestId { get; set; }
        public int branchId { get; set; }
        public int partyId { get; set; }
        public string guestName { get; set; }
        public string bookedBy { get; set; }
        public Nullable<int> departmentId { get; set; }
        public Nullable<int> carModelId { get; set; }
        public string contactNumber1 { get; set; }
        public string contactNumber2 { get; set; }
        public bool active { get; set; }
        public int entryBy { get; set; }
        public System.DateTime entryDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string contactNumber3 { get; set; }
        public string guestMobile { get; set; }
        public string bookedByMobile { get; set; }
    
        public virtual CarModel CarModel { get; set; }
        public virtual CompanyBranch CompanyBranch { get; set; }
        public virtual Department Department { get; set; }
        public virtual Party Party { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<guestAddress> guestAddresses { get; set; }
    }
}
