//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Party()
        {
            this.Guests = new HashSet<Guest>();
        }
    
        public int partyId { get; set; }
        public Nullable<int> branchId { get; set; }
        public string status { get; set; }
        public string Name { get; set; }
        public string billName { get; set; }
        public string idName { get; set; }
        public string address1 { get; set; }
        public string city1 { get; set; }
        public string pincode1 { get; set; }
        public string address2 { get; set; }
        public string city2 { get; set; }
        public string pincode2 { get; set; }
        public string contact1 { get; set; }
        public string contact2 { get; set; }
        public string faxNumber { get; set; }
        public string emailId { get; set; }
        public Nullable<int> primaryGroupId { get; set; }
        public bool discountAllowed { get; set; }
        public string dutySlipFormat { get; set; }
        public string vendorCode { get; set; }
        public string costCenter { get; set; }
        public Nullable<decimal> tdsPercent { get; set; }
        public Nullable<decimal> commissionPercent { get; set; }
        public string gstNumber { get; set; }
        public Nullable<bool> active { get; set; }
        public int entryBy { get; set; }
        public System.DateTime entryDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    
        public virtual CompanyBranch CompanyBranch { get; set; }
        public virtual PartyStatu PartyStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guest> Guests { get; set; }
    }
}
