//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateCard
    {
        public int rateId { get; set; }
        public System.DateTime efftectiveDate { get; set; }
        public Nullable<int> partyId { get; set; }
        public Nullable<int> carModelId { get; set; }
        public Nullable<int> dutyTypeId { get; set; }
        public Nullable<int> schemeId { get; set; }
        public Nullable<decimal> minHours { get; set; }
        public Nullable<decimal> minKm { get; set; }
        public Nullable<decimal> rateAmount { get; set; }
        public Nullable<decimal> extraHours { get; set; }
        public Nullable<decimal> extraKM { get; set; }
        public Nullable<decimal> nightAllowance { get; set; }
        public Nullable<decimal> dayAllowance { get; set; }
        public bool active { get; set; }
        public int entryBy { get; set; }
        public System.DateTime entryDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    
        public virtual CarModel CarModel { get; set; }
        public virtual DutyType DutyType { get; set; }
        public virtual Party Party { get; set; }
        public virtual Scheme Scheme { get; set; }
    }
}
